# Stage 1: Build the backend and name it "build"
FROM oven/bun:latest as build
WORKDIR /app
COPY server/package.json ./
RUN bun install
COPY server/ ./
RUN bun run bundle

# Stage 2: Run the backend
FROM oven/bun:latest
WORKDIR /app
# Copy the built app from the "build" stage
COPY --from=build /app/dist ./dist
COPY --from=build /app/node_modules ./node_modules
EXPOSE 3000
# Correctly start the app
CMD ["bun", "dist/app.js"]