# Stage 1: Build the frontend and name it "build"
FROM oven/bun:latest as build
WORKDIR /app
COPY client/package.json ./
RUN bun install
COPY client/ ./
RUN bun run build

# Stage 2: Serve the frontend with Nginx
FROM nginx:alpine
# Copy the built app from the "build" stage
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
